# Spring properties
spring:
  application:
     name: service-todo  # Service registers under this name
  freemarker:
    enabled: false           # Ignore Eureka dashboard FreeMarker templates
  thymeleaf:
    cache: false             # Allow Thymeleaf templates to be reloaded at runtime
  datasource:
    url: jdbc:postgresql://192.168.99.100:5432/cdf
    username: cdf
    password: cdf
  jackson:
    serialization:
      write_dates_as_timestamps: false
# These settings are used to autogenerate the database for us - a bit like using flyway only more simple.
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

server:
  port: 8081

# Map the error path to error template (for Thymeleaf)
error:
  path=/error

# Discovery Server Access
eureka:
    instance:
        leaseRenewalIntervalInSeconds: 3
        leaseExpirationDurationInSeconds: 2
        metadataMap:
            instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}

    client:
        registryFetchIntervalSeconds: 5
        instanceInfoReplicationIntervalSeconds: 5
        initialInstanceInfoReplicationIntervalSeconds: 5
        serviceUrl:
            defaultZone: ${vcap.services.${PREFIX:}eureka.credentials.uri:http://user:password@localhost:8080}/eureka/
        fetchRegistry: true
        healthcheck:
            enabled: true
